- name: loops in ansible
  hosts: mongodb, catalogue
  become: yes
  tasks:
  - name: install packages on mongodb
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    ansible.builtin.debug:
     msg: " installation of {{ item }} is successfull"
    loop:
    - nginx
    - telnet
    - zip
  - name: install packages on catalogue
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    ansible.builtin.debug:
     msg: " installation of {{ item }} is successfull"
    loop:
    - nodejs:20
    - mysql-server