- name: loops in ansible
  become: yes
  tasks:
  - name: install packages on mongodb
    hosts: mongodb
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - telnet
    - zip
  - name: install packages on catalogue
    hosts: catalogue
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nodejs:20
    - mysql-server