- name: Playlevel variables
  hosts: ansible
  connection: local
  vars_files:
  - vars.yml
  vars_prompt:
  - name: user
    prompt: Enter the user name
    private: false
  - name: password
    prompt: enter the password
    private: true
  tasks:
  - name: print the details
    ansible.builtin.debug:
      msg: " this is {{ course }} {{ Batch }} teach by {{ trainer }} {{ user }} {{ password }}"